# Generated by Django 2.2 on 2020-06-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_feels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feels',
            name='creator',
            field=models.ForeignKey(on_delete='CASCADE', related_name='feels_created', to='default.User'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete='CASCADE', related_name='comments_created', to='default.User')),
                ('feels', models.ForeignKey(on_delete='CASCADE', related_name='has_comments', to='default.Feels')),
            ],
        ),
    ]
