# Generated by Django 2.2 on 2020-06-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_auto_20200626_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.AddField(
            model_name='feels',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_feels', to='default.User'),
        ),
    ]
